language: node_js
node_js: 
  - "stable"
cache:
  directories:
    - "node_modules"
env:
  global:
    repo_token: O70vZohTvahFYOivB450PN1pTSadD0tk8
script:
 - npm run coveralls
 - npm run coverage
after_script:
  "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"
