language: node_js
node_js: 
  - "stable"
cache:
  directories:
    - "node_modules"
addons:
  code_climate:
    REPO_TOKEN : process.env.CODE_CLIMATE
script:
 - npm run test
 - nyc cover [npm run test] -- -R spec
before_script:
  - npm install codeclimate-test-reporter nyc
after_script:
  - codeclimate-test-reporter < ./coverage/lcov.info
after_success:
 - npm run coverage

 - npm run coveralls

