language: node_js
node_js: 
  - "stable"
cache:
  directories:
    - "node_modules"
addons:
  code_climate:
    REPO_TOKEN : process.env.CODE_CLIMATE
script:
 - npm run test

before_script:
 - npm install codeclimate-test-reporter istanbul

after_success:
 - npm run coverage

 - npm run coveralls
 - codeclimate-test-reporter < ./coverage/lcov.info

