language: node_js
node_js: 
  - "stable"
env:
  global:
    repo_token: O70vZohTvahFYOivB450PN1pTSadD0tk8
script:
 - npm run coveralls
 - npm run coverage
after_script:
   - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
